/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:271682672624:userpool/us-east-2_lCMLfl75W",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_lCMLfl75W",
    "aws_user_pools_web_client_id": "6a5dlenpbnlf8cn9o6dgs65m3l",
    "oauth": {}
};


export default awsmobile;
