/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4241e401-7e32-4657-8c66-754e097af455",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_q2rPhrV1Q",
    "aws_user_pools_web_client_id": "76i9itg2g763b8r6gc69vua9c6",
    "oauth": {}
};


export default awsmobile;
